/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: d89b39e7d6937edb876e51ad18480cce)
interface __BaseEnv_Env {
	KV: KVNamespace;
	DB: D1Database;
	NOTIFY_DISPATCH_QUEUE: Queue;
	NOTIFY_DELIVERY_QUEUE: Queue;
	ASSETS: Fetcher;
	WECHAT_CALLBACK_MAX_SKEW_SEC: "300";
	RECONCILE_AFTER_SEC: "120";
	RECONCILE_BATCH_SIZE: "50";
	CF_AUTH_ISSUER: "https://cf-auth.ehzyil.cc.cd";
	EGRESS_TIMEOUT_MS: "10000";
	SUBSCRIPTIONS_DEFAULT_OPEN: "false";
	ENFORCE_USER_SERVICE_MEMBERSHIP: "true";
	CF_AUTH_JWT_SECRET: string;
	WECHAT_TOKEN: string;
	WECHAT_APP_ID: string;
	WECHAT_AES_KEY: string;
	WECHAT_QRCODE_URL: string;
	WECHAT_DEFAULT_TEMPLATE_ID: string;
	EGRESS_BASE_URL: string;
	EGRESS_SHARED_SECRET: string;
	ADMIN_BOOTSTRAP_KEY: string;
	ALLOW_TEST_TOKEN: string;
	BIND_CODE_TTL_SEC: string;
	WECHAT_CODE_LOGIN_ENABLED: string;
	CF_AUTH: Fetcher /* cf-auth */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WECHAT_CALLBACK_MAX_SKEW_SEC" | "RECONCILE_AFTER_SEC" | "RECONCILE_BATCH_SIZE" | "CF_AUTH_ISSUER" | "EGRESS_TIMEOUT_MS" | "SUBSCRIPTIONS_DEFAULT_OPEN" | "ENFORCE_USER_SERVICE_MEMBERSHIP" | "CF_AUTH_JWT_SECRET" | "WECHAT_TOKEN" | "WECHAT_APP_ID" | "WECHAT_AES_KEY" | "WECHAT_QRCODE_URL" | "WECHAT_DEFAULT_TEMPLATE_ID" | "EGRESS_BASE_URL" | "EGRESS_SHARED_SECRET" | "ADMIN_BOOTSTRAP_KEY" | "ALLOW_TEST_TOKEN" | "BIND_CODE_TTL_SEC" | "WECHAT_CODE_LOGIN_ENABLED">> {}
}
