/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4dcebebc17912cb71fff35690c328fd5)
interface __BaseEnv_Env {
	KV: KVNamespace;
	DB: D1Database;
	NOTIFY_DISPATCH_QUEUE: Queue;
	NOTIFY_DELIVERY_QUEUE: Queue;
	ASSETS: Fetcher;
	WECHAT_CALLBACK_MAX_SKEW_SEC: "300";
	RECONCILE_AFTER_SEC: "120";
	RECONCILE_BATCH_SIZE: "50";
	CF_AUTH_ISSUER: "https://cf-auth.ehzyil.cc.cd";
	CF_AUTH_ACCOUNT_URL: "https://cf-auth.ehzyil.cc.cd/#notifications";
	ADMIN_OAUTH_CLIENT_ID: "cf-notify-admin";
	EGRESS_TIMEOUT_MS: "10000";
	SUBSCRIPTIONS_DEFAULT_OPEN: "false";
	NOTIFICATION_DIRECTORY_MODE: "rpc";
	WECHAT_PROVIDER_ACCOUNT_ID: "wechat-main";
	WECHAT_SEND_MODE: "custom_text";
	WECOM_CALLBACK_MAX_SKEW_SEC: "300";
	WECOM_PROVIDER_ACCOUNT_ID: "wecom-main";
	WECOM_CORP_ID: "ww37c322e2b04fab42";
	WECOM_ACCOUNT_NAME: "ehzyil的快乐星球";
	WECOM_QRCODE_URL: "https://cf-notify.ehzyil.cc.cd/channel-assets/wecom-join.jpg";
	WECOM_CALLBACK_TOKEN: "5MLYQmBmvofu2yDqGWTn";
	WECOM_ENCODING_AES_KEY: "1MiJizUGkfL9BSCKmmIFPbLqaDAnRXKBsGjqDSKdFa9";
	WECHAT_TOKEN: string;
	WECHAT_APP_ID: string;
	WECHAT_AES_KEY: string;
	WECHAT_QRCODE_URL: string;
	WECHAT_DEFAULT_TEMPLATE_ID: string;
	EGRESS_BASE_URL: string;
	EGRESS_SHARED_SECRET: string;
	CF_AUTH: Service /* entrypoint NotificationDirectory from cf-auth */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WECHAT_CALLBACK_MAX_SKEW_SEC" | "RECONCILE_AFTER_SEC" | "RECONCILE_BATCH_SIZE" | "CF_AUTH_ISSUER" | "CF_AUTH_ACCOUNT_URL" | "ADMIN_OAUTH_CLIENT_ID" | "EGRESS_TIMEOUT_MS" | "SUBSCRIPTIONS_DEFAULT_OPEN" | "NOTIFICATION_DIRECTORY_MODE" | "WECHAT_PROVIDER_ACCOUNT_ID" | "WECHAT_SEND_MODE" | "WECOM_CALLBACK_MAX_SKEW_SEC" | "WECOM_PROVIDER_ACCOUNT_ID" | "WECOM_CORP_ID" | "WECOM_ACCOUNT_NAME" | "WECOM_QRCODE_URL" | "WECOM_CALLBACK_TOKEN" | "WECOM_ENCODING_AES_KEY" | "WECHAT_TOKEN" | "WECHAT_APP_ID" | "WECHAT_AES_KEY" | "WECHAT_QRCODE_URL" | "WECHAT_DEFAULT_TEMPLATE_ID" | "EGRESS_BASE_URL" | "EGRESS_SHARED_SECRET">> {}
}
